title: Rowan Allan
logo: avatar.png
remote_theme: pages-themes/minimal@v0.2.0

description: >
  <strong>ML-Omics Scientist</strong><br>  
  <a href="mailto:rowanallan11@gmail.com">rowanallan11@gmail.com</a><br>
  <a href="https://github.com/RowanAllan11">GitHub</a><br>
  <a href="https://www.linkedin.com/in/rowan-allan1">LinkedIn</a> 
  <br> <br>
  <strong>Executive Summary:</strong> A research scientist with expertise at the intersection of AI, biology, and healthcare.
  <br> <br>
  Education: <br>  
  <strong>Imperial College London</strong> (Machine Learning)
  <strong>University of Galway</strong> (Genetics & Genomics)
  <br> <br>


